### ISSUE TITLE
What's the include logic? For example, adfront3.cpp doesn't include adfront3.hpp.

### ISSUE THREAD

**Issue by Mathias-Fuchs** [NGSolve/netgen#117]
That seems a little .... unorthodox. Is it intended? What's the logic behind a source file not including its header?
Also, why are there two files named myadt.hpp, where one includes the other?

**Comment by mhochsteger** [comment]
For each subdirectory in src/libsrc there is a "master" header in src/include, including all headers of this subdirectory for convenience. That's why adfront3.cpp only needs "meshing.hpp". I agree that this is unusual and might change in the future. The newer code in libsrc/core for instance has self-sufficient headers.

For the two headers: They are installed to different directories (leading to the same directory structure than in the source tree). Dependencies only need to pass the "include" directory to the compiler.

**Comment by Mathias-Fuchs** [comment]
I see, thanks for the explanation. However, this leads to the funny situation where many header files are not self-contained: they don't include headers they need; for instance meshing3.hpp does not include adfront3.hpp because it just expects to be in a compilation unit that includes the "master header". This makes it not so easy to understand the include graph ...
By the way, is it on purpose there are two files with the same name that seem to provide similar code: core/table.cpp and general/table.cpp?

**Comment by ChrLackner** [comment]
Yes, there is some old rarely tested code depending on the different versions on which some people might depend, maybe there will be some time to refactor that in the future.
