### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by looooo** [NGSolve/netgen#12]
I would like to add netgen to the conda-forge channel. Currently there are several netgen-packages available with conda:
- https://anaconda.org/mhochsteger/netgen
- https://anaconda.org/cad/netgen
- https://anaconda.org/pythonocc/netgen

Maybe we could try to combine this packages and make one that is more official and satisfy all the needs of the dependent libraries.

**Comment by looooo** [comment]
https://github.com/conda-forge/staged-recipes/pull/5320

**Comment by CJ-Wright** [comment]
It would be nice to have release tags too (xref: https://github.com/NGSolve/netgen/issues/8)

**Comment by looooo** [comment]
should netgen work on 32 bit windows? https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.22014/job/2tw3q4gjf6u1iy6w I disable it for now. Also the finding tk seems difficult for windows. So I disabled gui for windows.

**Comment by mhochsteger** [comment]
@looooo 
- Win32 is not (anymore) officially supported. The problem in your case is the compiler ("Internal compiler error"). Any good reason you still need to support it?
- GUI on Windows has another problem: In order to build togl we need internal tcl/tk headers, which are not available. I also couldn't find any conda packages for togl.
- You got a merge request for small changes.

**Comment by looooo** [comment]
Some people still using freecad with win32... It's not a big issue if win32 is not supported by netgen.

**Comment by looooo** [comment]
conda package of netgen-6.2.0-1802 is now uploaded:
```conda install netgen -c conda-forge```

@mhochsteger @JSchoeberl 
pyocct still needs https://github.com/NGSolve/netgen/pull/10 .
Maybe it's possible to merge the PR in the next release.
