### ISSUE TITLE
Environment variable NGS_NUM_THREADS not respected

### ISSUE THREAD

**Issue by jg-92** [NGSolve/netgen#36]
I currently have the problem that the environment variable NGS_NUM_THREADS is not respected when running netgen:

```
> export NGS_NUM_THREADS=1                                                                                
> netgen -geofile=/usr/share/netgen/torus.geo -meshfile=out.mesh -batchmode 
NETGEN-6.2-dev
Developed by Joachim Schoeberl at
2010-xxxx Vienna University of Technology
2006-2010 RWTH Aachen University
1996-2006 Johannes Kepler University Linz
Including OpenCascade geometry kernel
optfile ./ng.opt does not exist - using default values
togl-version : 2
no OpenGL
OCC module loaded
 Load CSG geometry file /usr/share/netgen/torus.geo
 Calc Triangle Approximation
 Object 0 has 882 triangles
[...]
task-based parallelization (C++11 threads) using 4 threads
[...]
task-based parallelization (C++11 threads) using 4 threads
[...]
```

Am I missing something out? Thanks!

**Comment by mhochsteger** [comment]
Hi,

since parts of the mesh generation are now parallel, Netgen introduced new settings in the meshing parameters to control multithreading. You can set it in the GUI in Mesh->Meshing Options -> Parallel meshing / Number of meshing threads. To make the setting persistent, you can store the options in File->Save options, which will create a ng.opt file in the current directory.
